[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Rp3"
authors = [{name = "Eduardo Vieira de Souza", email = "vdseduardo@gmail.com"}]
dynamic = ["version", "description"]
